<?php
/**
 * Errors automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Errors implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<Error>|null
     */
    #[Description('')]
    protected ?array $errors = null;
    /**
     * @param array<Error>|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }
    /**
     * @return array<Error>|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('errors', $this->errors);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
