<?php
/**
 * HideReplyResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;

#[Description('')]
class HideReplyResponse implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?HideReplyUpdate $data = null;
    public function setData(?HideReplyUpdate $data) : void
    {
        $this->data = $data;
    }
    public function getData() : ?HideReplyUpdate
    {
        return $this->data;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('data', $this->data);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
