<?php
/**
 * SingleTweet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class SingleTweet implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('tweet_id')]
    #[Description('')]
    protected ?string $tweetId = null;
    public function setTweetId(?string $tweetId) : void
    {
        $this->tweetId = $tweetId;
    }
    public function getTweetId() : ?string
    {
        return $this->tweetId;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('tweet_id', $this->tweetId);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
