<?php
/**
 * Trend automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class Trend implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('trend_name')]
    #[Description('')]
    protected ?string $trendName = null;
    #[Key('tweet_count')]
    #[Description('')]
    protected ?int $tweetCount = null;
    public function setTrendName(?string $trendName) : void
    {
        $this->trendName = $trendName;
    }
    public function getTrendName() : ?string
    {
        return $this->trendName;
    }
    public function setTweetCount(?int $tweetCount) : void
    {
        $this->tweetCount = $tweetCount;
    }
    public function getTweetCount() : ?int
    {
        return $this->tweetCount;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('trend_name', $this->trendName);
        $record->put('tweet_count', $this->tweetCount);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
