<?php
/**
 * TweetPoll automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class TweetPoll implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('duration_minutes')]
    #[Description('Duration of the poll in minutes for a Tweet with a poll. This is only required if the request includes poll.options.')]
    protected ?int $durationMinutes = null;
    /**
     * @var array<string>|null
     */
    #[Description('A list of poll options for a Tweet with a poll. For the request to be successful it must also include duration_minutes too.')]
    protected ?array $options = null;
    public function setDurationMinutes(?int $durationMinutes): void
    {
        $this->durationMinutes = $durationMinutes;
    }
    public function getDurationMinutes(): ?int
    {
        return $this->durationMinutes;
    }
    /**
     * @param array<string>|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }
    /**
     * @return array<string>|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('duration_minutes', $this->durationMinutes);
        $record->put('options', $this->options);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
