<?php
/**
 * TweetUsage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class TweetUsage implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('cap_reset_day')]
    #[Description('')]
    protected ?int $capResetDay = null;
    #[Key('project_cap')]
    #[Description('')]
    protected ?string $projectCap = null;
    #[Key('project_id')]
    #[Description('')]
    protected ?string $projectId = null;
    #[Key('project_usage')]
    #[Description('')]
    protected ?string $projectUsage = null;
    public function setCapResetDay(?int $capResetDay) : void
    {
        $this->capResetDay = $capResetDay;
    }
    public function getCapResetDay() : ?int
    {
        return $this->capResetDay;
    }
    public function setProjectCap(?string $projectCap) : void
    {
        $this->projectCap = $projectCap;
    }
    public function getProjectCap() : ?string
    {
        return $this->projectCap;
    }
    public function setProjectId(?string $projectId) : void
    {
        $this->projectId = $projectId;
    }
    public function getProjectId() : ?string
    {
        return $this->projectId;
    }
    public function setProjectUsage(?string $projectUsage) : void
    {
        $this->projectUsage = $projectUsage;
    }
    public function getProjectUsage() : ?string
    {
        return $this->projectUsage;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('cap_reset_day', $this->capResetDay);
        $record->put('project_cap', $this->projectCap);
        $record->put('project_id', $this->projectId);
        $record->put('project_usage', $this->projectUsage);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
