<?php
/**
 * UserTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class UserTag extends TagAbstract
{
    /**
     * @param string $userId
     * @param string|null $startTime
     * @param string|null $endTime
     * @param string|null $sinceId
     * @param string|null $untilId
     * @param string|null $exclude
     * @param string|null $expansions
     * @param int|null $maxResults
     * @param string|null $paginationToken
     * @param string|null $mediaFields
     * @param string|null $placeFields
     * @param string|null $pollFields
     * @param string|null $tweetFields
     * @param string|null $userFields
     * @return TweetCollectionResponse
     * @throws ClientException
     */
    public function getTimeline(string $userId, ?string $startTime = null, ?string $endTime = null, ?string $sinceId = null, ?string $untilId = null, ?string $exclude = null, ?string $expansions = null, ?int $maxResults = null, ?string $paginationToken = null, ?string $mediaFields = null, ?string $placeFields = null, ?string $pollFields = null, ?string $tweetFields = null, ?string $userFields = null): TweetCollectionResponse
    {
        $url = $this->parser->url('/2/users/:user_id/timelines/reverse_chronological', [
            'user_id' => $userId,
        ]);

        $options = [
            'query' => $this->parser->query([
                'start_time' => $startTime,
                'end_time' => $endTime,
                'since_id' => $sinceId,
                'until_id' => $untilId,
                'exclude' => $exclude,
                'expansions' => $expansions,
                'max_results' => $maxResults,
                'pagination_token' => $paginationToken,
                'media.fields' => $mediaFields,
                'place.fields' => $placeFields,
                'poll.fields' => $pollFields,
                'tweet.fields' => $tweetFields,
                'user.fields' => $userFields,
            ], [
            ]),
        ];

        try {
            $response = $this->httpClient->request('GET', $url, $options);
            $data = (string) $response->getBody();

            return $this->parser->parse($data, TweetCollectionResponse::class);
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }

    /**
     * Tweets liked by a user
     *
     * @param string $userId
     * @param string|null $expansions
     * @param int|null $maxResults
     * @param string|null $paginationToken
     * @param string|null $mediaFields
     * @param string|null $placeFields
     * @param string|null $pollFields
     * @param string|null $tweetFields
     * @param string|null $userFields
     * @return TweetCollectionResponse
     * @throws ClientException
     */
    public function getLikedTweets(string $userId, ?string $expansions = null, ?int $maxResults = null, ?string $paginationToken = null, ?string $mediaFields = null, ?string $placeFields = null, ?string $pollFields = null, ?string $tweetFields = null, ?string $userFields = null): TweetCollectionResponse
    {
        $url = $this->parser->url('/2/users/:user_id/liked_tweets', [
            'user_id' => $userId,
        ]);

        $options = [
            'query' => $this->parser->query([
                'expansions' => $expansions,
                'max_results' => $maxResults,
                'pagination_token' => $paginationToken,
                'media.fields' => $mediaFields,
                'place.fields' => $placeFields,
                'poll.fields' => $pollFields,
                'tweet.fields' => $tweetFields,
                'user.fields' => $userFields,
            ], [
            ]),
        ];

        try {
            $response = $this->httpClient->request('GET', $url, $options);
            $data = (string) $response->getBody();

            return $this->parser->parse($data, TweetCollectionResponse::class);
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }

    /**
     * @param string $userId
     * @param string $tweetId
     * @return LikeResponse
     * @throws ClientException
     */
    public function removeLike(string $userId, string $tweetId): LikeResponse
    {
        $url = $this->parser->url('/2/users/:user_id/likes/:tweet_id', [
            'user_id' => $userId,
            'tweet_id' => $tweetId,
        ]);

        $options = [
            'query' => $this->parser->query([
            ], [
            ]),
        ];

        try {
            $response = $this->httpClient->request('DELETE', $url, $options);
            $data = (string) $response->getBody();

            return $this->parser->parse($data, LikeResponse::class);
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }

    /**
     * @param string $userId
     * @param SingleTweet $payload
     * @return LikeResponse
     * @throws ClientException
     */
    public function createLike(string $userId, SingleTweet $payload): LikeResponse
    {
        $url = $this->parser->url('/2/users/:user_id/likes', [
            'user_id' => $userId,
        ]);

        $options = [
            'query' => $this->parser->query([
            ], [
            ]),
            'json' => $payload
        ];

        try {
            $response = $this->httpClient->request('POST', $url, $options);
            $data = (string) $response->getBody();

            return $this->parser->parse($data, LikeResponse::class);
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }


}
