<?php
/**
 * UserTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Twitter;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class UserTag extends TagAbstract
{
    /**
     * @param string $userId
     * @param string|null $expansions
     * @param string|null $tweetFields
     * @param string|null $userFields
     * @param int|null $maxResults
     * @return TweetCollectionResponse
     * @throws ClientException
     */
    public function getTimeline(string $userId, ?string $expansions = null, ?string $tweetFields = null, ?string $userFields = null, ?int $maxResults = null): TweetCollectionResponse
    {
        $url = $this->parser->url('/2/users/:user_id/timelines/reverse_chronological', [
            'user_id' => $userId,
        ]);

        $options = [
            'query' => $this->parser->query([
                'expansions' => $expansions,
                'tweet.fields' => $tweetFields,
                'user.fields' => $userFields,
                'max_results' => $maxResults,
            ]),
        ];

        try {
            $response = $this->httpClient->request('GET', $url, $options);
            $data = (string) $response->getBody();

            return $this->parser->parse($data, TweetCollectionResponse::class);
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }


}
